# 聊天格式
Format: "[%player_name%]"

# 是否开启聊天颜色
chatColor: true

#屏蔽脏话
replaceEnable: true
#遇到脏话时，转换为什么
replaceTo: "*"
#现已知的脏话列表，会转化为replaceTo
replaceWords:
  - "nm"
  - "sb"
  - "我操你大爷"

# 禁言列表
muteList:
  - "123"
  - "qwertyui"